// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-published-businesses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_published_businesses_default = defineTool({
  name: "list_published_businesses",
  title: "List published businesses",
  description: "List published businesses in the directory. Optionally filter by city, kind (restaurant/service), or a text search on name.",
  inputSchema: {
    city: z.string().optional().describe("Filter by city name."),
    kind: z.enum(["restaurant", "service"]).optional().describe("Filter by business kind."),
    search: z.string().optional().describe("Case-insensitive substring match on the business name."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, kind, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("businesses").select("id, slug, name, description, category, city, cuisine, kind, price_tier, address").eq("is_published", true).limit(limit ?? 20);
    if (city) query = query.eq("city", city);
    if (kind) query = query.eq("kind", kind);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { businesses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List bookings belonging to the signed-in user, most recent first.",
  inputSchema: {
    status: z2.enum(["pending", "confirmed", "cancelled", "completed"]).optional().describe("Filter by booking status."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("bookings").select("id, business_id, kind, service_id, table_id, start_time, end_time, party_size, status, price_cents, notes").eq("client_id", ctx.getUserId()).order("start_time", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/cancel-booking.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var cancel_booking_default = defineTool3({
  name: "cancel_booking",
  title: "Cancel booking",
  description: "Cancel one of the signed-in user's bookings by id. Sets status to 'cancelled'.",
  inputSchema: {
    booking_id: z3.string().uuid().describe("The booking id to cancel.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ booking_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("bookings").update({ status: "cancelled" }).eq("id", booking_id).eq("client_id", ctx.getUserId()).select("id, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Booking not found or not owned by you." }], isError: true };
    return {
      content: [{ type: "text", text: `Booking ${data.id} cancelled.` }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = define_import_meta_env_default.VITE_SUPABASE_PROJECT_ID ?? "project-ref-unset";
var mcp_default = defineMcp({
  name: "book-dine-find-mcp",
  title: "Book, Dine & Find",
  version: "0.1.0",
  instructions: "Tools for the Book, Dine & Find app. Use `list_published_businesses` to browse restaurants and services, `list_my_bookings` to see the signed-in user's reservations, and `cancel_booking` to cancel one of their bookings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_published_businesses_default, list_my_bookings_default, cancel_booking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
