// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const RAW_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() ?? '';
const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim() ?? '';
const SUPABASE_URL = RAW_SUPABASE_URL || (PROJECT_ID ? `https://${PROJECT_ID}.supabase.co` : '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ?? '';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseStub(): SupabaseClient<Database> {
  let warned = false;

  const warnOnce = (method: string) => {
    if (!warned) {
      warned = true;
      console.warn(
        `[supabase] Missing Supabase configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env.local before using ${method}.`
      );
    }
  };

  const throwConfigError = (method: string): never => {
    warnOnce(method);
    throw new Error(
      `Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env.local before using ${method}.`
    );
  };

  return {
    auth: {
      getSession: async () => throwConfigError('supabase.auth.getSession'),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe() {},
          },
        },
      }),
      signOut: async () => throwConfigError('supabase.auth.signOut'),
      signInWithPassword: async () => throwConfigError('supabase.auth.signInWithPassword'),
      signInWithOtp: async () => throwConfigError('supabase.auth.signInWithOtp'),
      signUp: async () => throwConfigError('supabase.auth.signUp'),
    },
    functions: {
      invoke: async () => throwConfigError('supabase.functions.invoke'),
    },
    from: () => throwConfigError('supabase.from'),
    channel: () => throwConfigError('supabase.channel'),
    removeChannel: () => throwConfigError('supabase.removeChannel'),
  } as unknown as SupabaseClient<Database>;
}

const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createSupabaseStub();

export { isSupabaseConfigured };
